version: '3'
services:
  web:
    image: nginx:latest
    restart: always
    ports: 
      - "8100:80"
    volumes:
      - ./app:/app
      - ./default.conf:/etc/nginx/conf.d/default.conf
  php:
    image: php:7-fpm
    volumes:
      - ./app:/app
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: docker42
  adminer:
    image: adminer
    restart: always
    ports:
      - 8101:8080